# Урок 4
Эта демонстрация разбита на 3 ноутбука:

1. **Свертки и пулинги.**
2. Даталоадеры.
3. Задача классификации с использованием CNN.

## Свертки и пулинги в PyTorch

Рассмотрим работу Conv2d и Pooling в PyTorch.

### Свертки

In [1]:
import torch
import torch.nn as nn

# В nn лежит Conv2d и Conv1d.
# Conv2d работает с картниками и его ядро является квадратом.
# Conv1d работает с последовательностями и его ядро является отрезком.
conv_layer = nn.Conv2d(
    in_channels=1,
    # число ядер
    out_channels=1,
    kernel_size=2,
    stride=1,
    padding=0,
    dilation=1,
    bias=False,
)
# Явно проставим веса в ядре
with torch.no_grad():
    conv_layer.weight = nn.Parameter(
        torch.ones((1, 1, 2, 2)) + torch.eye(2)[None, None, ...]
    )
data = torch.arange(3 * 3, dtype=torch.float32).reshape((1, 1, 3, 3))
print(data)
print(conv_layer.weight)
# Сравним выход с тем, что подсчитаем вручную.
print(conv_layer(data))

tensor([[[[0., 1., 2.],
          [3., 4., 5.],
          [6., 7., 8.]]]])
Parameter containing:
tensor([[[[2., 1.],
          [1., 2.]]]], requires_grad=True)
tensor([[[[12., 18.],
          [30., 36.]]]], grad_fn=<ConvolutionBackward0>)


In [2]:
# Свертка реализована еще и как отдельная операция
import torch.nn.functional as F

F.conv2d(data, weight=torch.ones((1, 1, 2, 2)) + torch.eye(2)[None, None, ...])
# Слой Conv2d - это, по сути, обертка над F.conv2d

tensor([[[[12., 18.],
          [30., 36.]]]])

### Pooling

Пулингов в PyTorch много:
- `MaxPool2d` - пройтись по ядру и взять максимум;
- `AvgPool2d` - пройтись по ядру и взять среднее;
- `AdaptiveMaxPool2d` - пройтись по **всей** картинке и взять максимум;
- `AdaptiveAvgPool2d` - пройтись по **всей** картинке и взять среднее.

Рассмотрим `MaxPool2d`, остальные аналогичны.

In [3]:
max_pool = nn.MaxPool2d(kernel_size=(2, 2))
print(data)
print(max_pool(data))
# В пулинге stride == kernel_size по умолчанию

tensor([[[[0., 1., 2.],
          [3., 4., 5.],
          [6., 7., 8.]]]])
tensor([[[[4.]]]])


In [4]:
bigger_data = torch.arange(4 * 4, dtype=torch.float32).reshape((1, 1, 4, 4))
print(bigger_data)
print(max_pool(bigger_data))

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])
tensor([[[[ 5.,  7.],
          [13., 15.]]]])
